### ISSUE TITLE
Node.js compatibility error

### ISSUE THREAD

**Issue by metaljay** [K1LL3R234/homebridge-texecom#13]
Just noticed the following error, are you getting the same?

```javascript
[12/16/2024, 4:05:07 PM] The plugin "homebridge-texecom-full" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF
[12/16/2024, 4:05:07 PM] ====================
[12/16/2024, 4:05:07 PM] ERROR LOADING PLUGIN homebridge-texecom-full:
[12/16/2024, 4:05:07 PM] Error: The module '/homebridge/node_modules/homebridge-texecom-full/node_modules/@serialport/bindings/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 115. This version of Node.js requires
NODE_MODULE_VERSION 127. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object..node (node:internal/modules/cjs/loader:1734:18)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:138:16)
    at bindings (/homebridge/node_modules/homebridge-texecom-full/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-texecom-full/node_modules/@serialport/bindings/lib/linux.js:2:36)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
[12/16/2024, 4:05:07 PM] ====================
```

**Comment by K1LL3R234** [comment]
Yes I had the same issue and don't know how to fix it yet. I had to downgrade back to 20.18.1.

The command is `hb-service update-node 20.18.1`

**Comment by metaljay** [comment]
I don't pretend to know how to code, but looking at the error is it not just a matter of re-compiling your code against the new node.js dependancy?

**Comment by K1LL3R234** [comment]
Thank you I will give it a shot and let you know. ASAP

**Comment by K1LL3R234** [comment]
Do you use Serial port or IP?

**Comment by K1LL3R234** [comment]
I think I fixed it with a beta release please let me know

**Comment by metaljay** [comment]
tested 4.2.5 beta 1 and all working good. 
Yes I am on serial port.

Great job!
